name: open_meteo_api
description: "A Flutter API client for Open-Meteo API"
version: 0.0.1

environment:
  sdk: ^3.6.1

dependencies:
  http:
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:
  mocktail:
  test: