name: open_meteo_api
description: "A Flutter API client for Open-Meteo API"
version: 0.0.1

environment:
  sdk: ^3.6.1

dependencies:
  json_annotation: ^4.9.0
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15
